name: CI

on:
  push:
    branches:
      - main # ou a branch principal do seu projeto
  pull_request:
    branches:
      - main # ou a branch principal do seu projeto

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Use a versão do Node.js que você está utilizando

      - name: Install dependencies
        run: |
          npm install

      - name: Run tests
        run: |
          npm test
